services:
  - type: web
    name: zaidy-difranco
    env: static
    buildCommand: echo "Building static site..."
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
